"""Stable device boundary; providers never access this interface."""

from __future__ import annotations

from typing import Protocol
from ..state.models import RawDeviceState


class DeviceAdapter(Protocol):
    async def observe(self) -> RawDeviceState: ...
    async def tap(self, target: str) -> None: ...
    async def long_press(self, target: str) -> None: ...
    async def type_text(self, text: str, target: str | None = None) -> None: ...
    async def swipe(self, direction: str) -> None: ...
    async def back(self) -> None: ...
    async def launch_app(self, package: str) -> None: ...
    async def screenshot(self) -> bytes: ...
