"""Stable device boundary; providers never access this interface."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol
from ..state.models import RawDeviceState


@dataclass(frozen=True, slots=True)
class MutationReceipt:
    """An acknowledgement, never proof that Android made the desired change."""

    request_id: str
    status: str
    sequence_before: int | None = None


class MutationRejected(Exception):
    """The bridge rejected a mutation before it could be scheduled."""


class MutationOutcomeUnknown(Exception):
    """Transport failed after a mutation may already have reached Android."""


class DeviceAdapter(Protocol):
    async def observe(self) -> RawDeviceState: ...
    async def tap(self, target: str) -> MutationReceipt | None: ...
    async def long_press(self, target: str) -> None: ...
    async def type_text(self, text: str, target: str | None = None) -> MutationReceipt | None: ...
    async def append_text(self, text: str, target: str | None = None) -> MutationReceipt | None: ...
    async def clear_text(self, target: str | None = None) -> MutationReceipt | None: ...
    async def swipe(self, direction: str) -> None: ...
    async def back(self) -> None: ...
    async def home(self) -> None: ...
    async def launch_app(self, package: str) -> None: ...
    async def open_app_root(self, package: str) -> None: ...
    async def reset_app_task(self, package: str) -> None: ...
    async def restart_app_process(self, package: str) -> None: ...
    async def screenshot(self) -> bytes: ...
